spring.application.name=prontus

spring.datasource.url=jdbc:postgresql://localhost:5433/prontus
spring.datasource.username=prontus
spring.datasource.password=prontus123
spring.datasource.driver-class-name=org.postgresql.Driver

# Flyway (entra em ação quando criarmos V1__initial.sql)
spring.flyway.enabled=true

# Desativa a Security temporariamente (como já fizemos)
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

# Threads virtuais do Java 21
spring.threads.virtual.enabled=true
