spring.application.name=prontus

spring.datasource.url=jdbc:postgresql://localhost:5433/prontus
spring.datasource.username=prontus
spring.datasource.password=prontus123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

spring.threads.virtual.enabled=true

spring.jpa.hibernate.ddl-auto=validate

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tags-sorter=alpha

jwt.secret=${JWT_SECRET}
jwt.expiration-minutes=120

admin.username=admin
admin.password=${ADMIN_PASSWORD:admin-prontus-2026}

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.consumer.group-id=prontus-queue
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=br.com.fiap.prontus.shared.events
spring.kafka.consumer.properties.spring.json.value.default.type=br.com.fiap.prontus.shared.events.PatientTriagedEvent