spring.application.name=prontus

spring.datasource.url=jdbc:postgresql://localhost:5433/prontus
spring.datasource.username=prontus
spring.datasource.password=prontus123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

spring.threads.virtual.enabled=true

spring.jpa.hibernate.ddl-auto=validate